### ISSUE TITLE
TopologyException.RuntimeException

### ISSUE THREAD

**Issue by mortenbo** [shopgun/goatsheep#1]
## Input

```json
{
	"width": 359,
	"height": 171.5,
	"contours": [
		[{
			"x": -5.65625,
			"y": 110.828125
		}, {
			"x": -7.53125,
			"y": 202.234375
		}, {
			"x": 366.0625,
			"y": 202.234375
		}, {
			"x": 356.6875,
			"y": 65.828125
		}, {
			"x": 260.125,
			"y": 59.265625
		}, {
			"x": 253.09375,
			"y": 40.984375
		}, {
			"x": 189.34375,
			"y": 19.890625
		}, {
			"x": 141.0625,
			"y": 36.765625
		}, {
			"x": 111.53125,
			"y": 6.765625
		}, {
			"x": 73.5625,
			"y": 36.765625
		}, {
			"x": 67.46875,
			"y": 10.984375
		}, {
			"x": 41.21875,
			"y": 10.515625
		}, {
			"x": 36.0625,
			"y": 42.390625
		}, {
			"x": 65.59375,
			"y": 53.171875
		}]
	],
	"objects": [{
		"width": 100,
		"height": 40
	}],
	"exclude": [{
		"top": -21.828125,
		"left": 8,
		"width": 180,
		"height": 180
	}, {
		"top": 0,
		"left": 0,
		"width": 375,
		"height": 37.5
	}, {
		"top": 0,
		"left": 367,
		"width": 8,
		"height": 187.5
	}, {
		"top": 179.5,
		"left": 0,
		"width": 375,
		"height": 8
	}, {
		"top": 0,
		"left": 0,
		"width": 8,
		"height": 187.5
	}]
}
```

## Output

```
[goatsheep] @turf/intersection threw an Error:
{ Error
    at TopologyException.RuntimeException [as constructor] (/Users/mbor/Code/shopgun-bumblebee/node_modules/turf-jsts/jsts.js:2168:19)
    at new TopologyException (/Users/mbor/Code/shopgun-bumblebee/node_modules/turf-jsts/jsts.js:8106:25)
    at DirectedEdgeStar.linkResultDirectedEdges (/Users/mbor/Code/shopgun-bumblebee/node_modules/turf-jsts/jsts.js:13021:38)
    at Function.linkResultDirectedEdges (/Users/mbor/Code/shopgun-bumblebee/node_modules/turf-jsts/jsts.js:9479:21)
    at PolygonBuilder.add (/Users/mbor/Code/shopgun-bumblebee/node_modules/turf-jsts/jsts.js:9620:17)
    at PolygonBuilder.add (/Users/mbor/Code/shopgun-bumblebee/node_modules/turf-jsts/jsts.js:9616:10)
    at OverlayOp.computeOverlay (/Users/mbor/Code/shopgun-bumblebee/node_modules/turf-jsts/jsts.js:18074:17)
    at OverlayOp.getResultGeometry (/Users/mbor/Code/shopgun-bumblebee/node_modules/turf-jsts/jsts.js:18043:10)
    at Function.OverlayOp.overlayOp (/Users/mbor/Code/shopgun-bumblebee/node_modules/turf-jsts/jsts.js:18166:20)
    at SnapIfNeededOverlayOp.getResultGeometry (/Users/mbor/Code/shopgun-bumblebee/node_modules/turf-jsts/jsts.js:16993:24)
  name: 'TopologyException',
  message: 'no outgoing dirEdge found',
  stack: 'Error\n    at TopologyException.RuntimeException [as constructor] (/Users/mbor/Code/shopgun-bumblebee/node_modules/turf-jsts/jsts.js:2168:19)\n    at new TopologyException (/Users/mbor/Code/shopgun-bumblebee/node_modules/turf-jsts/jsts.js:8106:25)\n    at DirectedEdgeStar.linkResultDirectedEdges (/Users/mbor/Code/shopgun-bumblebee/node_modules/turf-jsts/jsts.js:13021:38)\n    at Function.linkResultDirectedEdges (/Users/mbor/Code/shopgun-bumblebee/node_modules/turf-jsts/jsts.js:9479:21)\n    at PolygonBuilder.add (/Users/mbor/Code/shopgun-bumblebee/node_modules/turf-jsts/jsts.js:9620:17)\n    at PolygonBuilder.add (/Users/mbor/Code/shopgun-bumblebee/node_modules/turf-jsts/jsts.js:9616:10)\n    at OverlayOp.computeOverlay (/Users/mbor/Code/shopgun-bumblebee/node_modules/turf-jsts/jsts.js:18074:17)\n    at OverlayOp.getResultGeometry (/Users/mbor/Code/shopgun-bumblebee/node_modules/turf-jsts/jsts.js:18043:10)\n    at Function.OverlayOp.overlayOp (/Users/mbor/Code/shopgun-bumblebee/node_modules/turf-jsts/jsts.js:18166:20)\n    at SnapIfNeededOverlayOp.getResultGeometry (/Users/mbor/Code/shopgun-bumblebee/node_modules/turf-jsts/jsts.js:16993:24)',
  pt: Coordinate { x: 88.374079, y: 25.062649000000004, z: undefined } }
```

**Comment by mortenbo** [comment]
Other things I'm seeing: ```
[goatsheep] @turf/intersection threw an Error:
{ Error
    at TopologyException.RuntimeException [as constructor](/Users/mbor/Code/shopgun-bumblebee/node_modules/turf-jsts/jsts.js:2168:19)
    at new TopologyException (/Users/mbor/Code/shopgun-bumblebee/node_modules/turf-jsts/jsts.js:8106:25)
    at DirectedEdgeStar.linkResultDirectedEdges (/Users/mbor/Code/shopgun-bumblebee/node_modules/turf-jsts/jsts.js:13021:38)
    at Function.linkResultDirectedEdges (/Users/mbor/Code/shopgun-bumblebee/node_modules/turf-jsts/jsts.js:9479:21)
    at PolygonBuilder.add (/Users/mbor/Code/shopgun-bumblebee/node_modules/turf-jsts/jsts.js:9620:17)
    at PolygonBuilder.add (/Users/mbor/Code/shopgun-bumblebee/node_modules/turf-jsts/jsts.js:9616:10)
    at OverlayOp.computeOverlay (/Users/mbor/Code/shopgun-bumblebee/node_modules/turf-jsts/jsts.js:18074:17)
    at OverlayOp.getResultGeometry (/Users/mbor/Code/shopgun-bumblebee/node_modules/turf-jsts/jsts.js:18043:10)
    at Function.OverlayOp.overlayOp (/Users/mbor/Code/shopgun-bumblebee/node_modules/turf-jsts/jsts.js:18166:20)
    at SnapIfNeededOverlayOp.getResultGeometry (/Users/mbor/Code/shopgun-bumblebee/node_modules/turf-jsts/jsts.js:16993:24)
  name: 'TopologyException',
  message: 'no outgoing dirEdge found',
  stack: 'Error\n    at TopologyException.RuntimeException[as constructor] (/Users/mbor/Code/shopgun-bumblebee/node_modules/turf-jsts/jsts.js:2168:19)\n    at new TopologyException (/Users/mbor/Code/shopgun-bumblebee/node_modules/turf-jsts/jsts.js:8106:25)\n    at DirectedEdgeStar.linkResultDirectedEdges (/Users/mbor/Code/shopgun-bumblebee/node_modules/turf-jsts/jsts.js:13021:38)\n    at Function.linkResultDirectedEdges (/Users/mbor/Code/shopgun-bumblebee/node_modules/turf-jsts/jsts.js:9479:21)\n    at PolygonBuilder.add (/Users/mbor/Code/shopgun-bumblebee/node_modules/turf-jsts/jsts.js:9620:17)\n    at PolygonBuilder.add (/Users/mbor/Code/shopgun-bumblebee/node_modules/turf-jsts/jsts.js:9616:10)\n    at OverlayOp.computeOverlay (/Users/mbor/Code/shopgun-bumblebee/node_modules/turf-jsts/jsts.js:18074:17)\n    at OverlayOp.getResultGeometry (/Users/mbor/Code/shopgun-bumblebee/node_modules/turf-jsts/jsts.js:18043:10)\n    at Function.OverlayOp.overlayOp (/Users/mbor/Code/shopgun-bumblebee/node_modules/turf-jsts/jsts.js:18166:20)\n    at SnapIfNeededOverlayOp.getResultGeometry (/Users/mbor/Code/shopgun-bumblebee/node_modules/turf-jsts/jsts.js:16993:24)',
  pt: Coordinate { x: 88.374079, y: 25.062649000000004, z:undefined } }
TypeError: Cannot read property 'cell' of undefined
    at Critic.getSolutionDistance (/Users/mbor/Code/shopgun-bumblebee/node_modules/goatsheep/lib/critic.js:22:53)
    at distancesToOtherObjects.goatsheep.solutions.map (/Users/mbor/Code/shopgun-bumblebee/node_modules/goatsheep/lib/critic.js:37:59)
    at Array.map (<anonymous>)
    at Critic.calculatePositionScore (/Users/mbor/Code/shopgun-bumblebee/node_modules/goatsheep/lib/critic.js:36:70)
    at Critic.critiquePosition (/Users/mbor/Code/shopgun-bumblebee/node_modules/goatsheep/lib/critic.js:10:14)
    at Array.map (<anonymous>)
    at Analysis.analyze (/Users/mbor/Code/shopgun-bumblebee/node_modules/goatsheep/lib/analysis.js:19:39)
    at Analysis.goatsheep.objects.forEach (/Users/mbor/Code/shopgun-bumblebee/node_modules/goatsheep/lib/analysis.js:10:66)
    at Array.forEach (<anonymous>)
    at new Analysis (/Users/mbor/Code/shopgun-bumblebee/node_modules/goatsheep/lib/analysis.js:9:27)
TypeError: Cannot read property 'cell' of undefined
    at Critic.getSolutionDistance (/Users/mbor/Code/shopgun-bumblebee/node_modules/goatsheep/lib/critic.js:22:53)
    at distancesToOtherObjects.goatsheep.solutions.map (/Users/mbor/Code/shopgun-bumblebee/node_modules/goatsheep/lib/critic.js:37:59)
    at Array.map (<anonymous>)
    at Critic.calculatePositionScore (/Users/mbor/Code/shopgun-bumblebee/node_modules/goatsheep/lib/critic.js:36:70)
    at Critic.critiquePosition (/Users/mbor/Code/shopgun-bumblebee/node_modules/goatsheep/lib/critic.js:10:14)
    at Array.map (<anonymous>)
    at Analysis.analyze (/Users/mbor/Code/shopgun-bumblebee/node_modules/goatsheep/lib/analysis.js:19:39)
    at Analysis.goatsheep.objects.forEach (/Users/mbor/Code/shopgun-bumblebee/node_modules/goatsheep/lib/analysis.js:10:66)
    at Array.forEach (<anonymous>)
    at new Analysis (/Users/mbor/Code/shopgun-bumblebee/node_modules/goatsheep/lib/analysis.js:9:27)
TypeError: Cannot read property 'cell' of undefined
    at Critic.getSolutionDistance (/Users/mbor/Code/shopgun-bumblebee/node_modules/goatsheep/lib/critic.js:22:53)
    at distancesToOtherObjects.goatsheep.solutions.map (/Users/mbor/Code/shopgun-bumblebee/node_modules/goatsheep/lib/critic.js:37:59)
    at Array.map (<anonymous>)
    at Critic.calculatePositionScore (/Users/mbor/Code/shopgun-bumblebee/node_modules/goatsheep/lib/critic.js:36:70)
    at Critic.critiquePosition (/Users/mbor/Code/shopgun-bumblebee/node_modules/goatsheep/lib/critic.js:10:14)
    at Array.map (<anonymous>)
    at Analysis.analyze (/Users/mbor/Code/shopgun-bumblebee/node_modules/goatsheep/lib/analysis.js:19:39)
    at Analysis.goatsheep.objects.forEach (/Users/mbor/Code/shopgun-bumblebee/node_modules/goatsheep/lib/analysis.js:10:66)
    at Array.forEach (<anonymous>)
    at new Analysis (/Users/mbor/Code/shopgun-bumblebee/node_modules/goatsheep/lib/analysis.js:9:27)
TypeError: Cannot read property 'cell' of undefined
    at Critic.getSolutionDistance (/Users/mbor/Code/shopgun-bumblebee/node_modules/goatsheep/lib/critic.js:22:53)
    at distancesToOtherObjects.goatsheep.solutions.map (/Users/mbor/Code/shopgun-bumblebee/node_modules/goatsheep/lib/critic.js:37:59)
    at Array.map (<anonymous>)
    at Critic.calculatePositionScore (/Users/mbor/Code/shopgun-bumblebee/node_modules/goatsheep/lib/critic.js:36:70)
    at Critic.critiquePosition (/Users/mbor/Code/shopgun-bumblebee/node_modules/goatsheep/lib/critic.js:10:14)
    at Array.map (<anonymous>)
    at Analysis.analyze (/Users/mbor/Code/shopgun-bumblebee/node_modules/goatsheep/lib/analysis.js:19:39)
    at Analysis.goatsheep.objects.forEach (/Users/mbor/Code/shopgun-bumblebee/node_modules/goatsheep/lib/analysis.js:10:66)
    at Array.forEach (<anonymous>)
    at new Analysis (/Users/mbor/Code/shopgun-bumblebee/node_modules/goatsheep/lib/analysis.js:9:27)```

**Comment by izotos** [comment]
Using the latest [@turf/intersect](https://www.npmjs.com/package/@turf/intersect), which uses the [Martinez-Rueda polygon clipping algorithm](https://github.com/w8r/martinez/) yields an error in some cases, also using the aforementioned test data.

I've made an issue here https://github.com/w8r/martinez/issues/85.
